spring:
  application:
    name: user-interface-service
server:
  port: 8081
loadData:
  apiKey:
    daily: 6XAKFCNBJ16IVXO6
    intraDay: 4Z8RED01YJW9L47F
    currentDay: c0c2nen48v6o915a0hmg
  intraDayInterval: 5     #Valid Values: 1min, 5min, 15min, 30min, 60min